spring.application.name=banking-management-system
spring.datasource.url=jdbc:mysql://localhost:3306/banking_db
spring.datasource.username=root
spring.datasource.password=6878#6583@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true